version: '2'
services:
    gametree-app:
        image: gametree
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://gametree-mysql:3306/gametree?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    gametree-mysql:
        extends:
            file: mysql.yml
            service: gametree-mysql
